project:
  type: website
  output-dir: docs

website:
  repo-url: https://github.com/SemilleroCI/semillero
  repo-actions: [edit, issue]
  title: "Semillero Computer Vision"


  page-footer:
    left: |
      Desarrolado por:
      
    center:
      - text: "Github"
        href: github.com
      - text: "Youtube"
        href: youtube.com
      - text: "FAQ"
        href: faq.qmd

    right:  Â© 2024 Hands-on Computer Vision. Todos los derechos reservados. 
  


  sidebar:
    style: "floating"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


metadata-files:
  - navbar.yml
  - sidebar.yml

